---@meta

-- THIS FILE IS AUTO-GENERATED by `aberredengine --create-lua-stubs`.
-- DO NOT EDIT MANUALLY. Regenerate from engine.__meta instead.

---@class engine
---Engine API provided by Aberred Engine (Rust)
---All functions are available globally via the `engine` table
engine = {}

-- ==================== Types ====================

---2D vector / point
---@class Vector2
---@field x number
---@field y number

---Axis-aligned rectangle
---@class Rect
---@field x number
---@field y number
---@field w number
---@field h number

---Sprite state snapshot
---@class SpriteInfo
---@field tex_key string
---@field flip_h boolean
---@field flip_v boolean

---Animation state snapshot
---@class AnimationInfo
---@field key string
---@field frame_index integer
---@field elapsed number

---Lua timer state snapshot
---@class TimerInfo
---@field duration number
---@field elapsed number
---@field callback string

---Entity signal snapshot
---@class SignalSet
---@field flags string[]
---@field integers table<string, integer>
---@field scalars table<string, number>
---@field strings table<string, string>

---Entity state passed to phase/timer callbacks
---@class EntityContext
---@field id integer Entity ID
---@field group string|nil
---@field pos Vector2|nil
---@field screen_pos Vector2|nil
---@field vel Vector2|nil
---@field speed_sq number|nil
---@field frozen boolean|nil
---@field rotation number|nil
---@field scale Vector2|nil
---@field rect Rect|nil
---@field sprite SpriteInfo|nil
---@field animation AnimationInfo|nil
---@field signals SignalSet|nil
---@field phase string|nil
---@field time_in_phase number|nil
---@field previous_phase string|nil Only in on_enter
---@field timer TimerInfo|nil

---Entity data in a collision context
---@class CollisionEntity
---@field id integer Entity ID
---@field group string
---@field pos Vector2
---@field vel Vector2
---@field speed_sq number
---@field rect Rect
---@field signals SignalSet

---Collision contact sides
---@class CollisionSides
---@field a string[] Sides of entity A in contact
---@field b string[] Sides of entity B in contact

---Context passed to collision callbacks
---@class CollisionContext
---@field a CollisionEntity
---@field b CollisionEntity
---@field sides CollisionSides

---State of a single digital button
---@class DigitalButtonState
---@field pressed boolean
---@field just_pressed boolean
---@field just_released boolean

---All digital button states
---@class DigitalInputs
---@field up DigitalButtonState
---@field down DigitalButtonState
---@field left DigitalButtonState
---@field right DigitalButtonState
---@field action_1 DigitalButtonState
---@field action_2 DigitalButtonState
---@field back DigitalButtonState
---@field special DigitalButtonState

---Input state passed to callbacks
---@class InputSnapshot
---@field digital DigitalInputs
---@field analog table Reserved for future gamepad support

---Callbacks for a single phase
---@class PhaseCallbacks
---@field on_enter string|nil Function name called on phase enter
---@field on_update string|nil Function name called each frame
---@field on_exit string|nil Function name called on phase exit

---Phase state machine definition
---@class PhaseDefinition
---@field initial string Initial phase name
---@field phases table<string, PhaseCallbacks> Map of phase name to callbacks

---Particle emitter configuration table
---@class ParticleEmitterConfig
---@field templates string[] Entity template keys to emit
---@field shape string|nil Emitter shape: 'point' or 'rect'
---@field offset table|nil {x, y} offset from entity position
---@field particles_per_emission integer|nil
---@field emissions_per_second number|nil
---@field emissions_remaining integer|nil nil = infinite
---@field arc table|nil {min, max} angle in degrees
---@field speed table|nil {min, max} or single number
---@field ttl table|nil {min, max}, number, or 'none'

---Menu item definition
---@class MenuItem
---@field id string
---@field label string

---Animation rule condition (polymorphic)
---@class AnimationRuleCondition
---@field type string Condition type: has_flag, lacks_flag, scalar_cmp, scalar_range, integer_cmp, integer_range, all, any, not
---@field key string|nil Signal key (for flag/scalar/integer conditions)
---@field op string|nil Comparison operator (for cmp conditions)
---@field value number|nil Comparison value (for cmp conditions)
---@field min number|nil Range minimum (for range conditions)
---@field max number|nil Range maximum (for range conditions)
---@field conditions AnimationRuleCondition[]|nil Sub-conditions (for all/any/not)

-- ==================== Enums ====================

---Collision side
---@alias BoxSide "left" | "right" | "top" | "bottom"

---Function category
---@alias Category "base" | "asset" | "spawn" | "audio" | "signal" | "phase" | "entity" | "group" | "tilemap" | "camera" | "collision" | "animation" | "render"

---Comparison operator for animation rules
---@alias ComparisonOp "lt" | "le" | "gt" | "ge" | "eq" | "ne"

---Animation rule condition type
---@alias ConditionType "has_flag" | "lacks_flag" | "scalar_cmp" | "scalar_range" | "integer_cmp" | "integer_range" | "all" | "any" | "not"

---Tween easing function
---@alias Easing "linear" | "quad_in" | "quad_out" | "quad_in_out" | "cubic_in" | "cubic_out" | "cubic_in_out"

---Particle emitter shape type
---@alias EmitterShape "point" | "rect"

---Tween loop mode
---@alias LoopMode "once" | "loop" | "ping_pong"

---Time-to-live specification (number, {min,max} table, or 'none')
---@alias TtlSpec "none"

-- ==================== Callback Signatures ====================
-- These are the callback functions your Lua scripts should define.
-- They are called by the engine at appropriate times.

---Called once during game setup for asset loading
---Context: setup
function on_setup() end

---Called when entering Playing state
---Context: play
function on_enter_play() end

---Called when switching scenes
---Context: play
---@param scene string
function on_switch_scene(scene) end

---Called each frame during a scene
---NOTE: Function name is dynamic: on_update_ + scene name
---Context: play
--- param: input InputSnapshot
--- param: dt number
-- function on_update_<scene>(input, dt) end

---Called when entering a phase
---NOTE: Return phase name to trigger transition
---Context: play
---@param ctx EntityContext
---@param input InputSnapshot
---@return string|nil
function phase_on_enter(ctx, input) end

---Called each frame during a phase
---NOTE: Return phase name to trigger transition
---Context: play
---@param ctx EntityContext
---@param input InputSnapshot
---@param dt number
---@return string|nil
function phase_on_update(ctx, input, dt) end

---Called when exiting a phase
---Context: play
---@param ctx EntityContext
function phase_on_exit(ctx) end

---Called when a Lua timer fires
---Context: play
---@param ctx EntityContext
---@param input InputSnapshot
function timer_callback(ctx, input) end

---Called when two colliding groups overlap
---Context: play
---@param ctx CollisionContext
function collision_callback(ctx) end

---Called when a menu item is selected
---Context: play
---@param menu_id integer
---@param item_id string
---@param item_index integer
function menu_callback(menu_id, item_id, item_index) end

-- ==================== Logging Functions ====================

---General purpose logging
---@param message string
function engine.log(message) end

---Error level logging
---@param message string
function engine.log_error(message) end

---Info level logging
---@param message string
function engine.log_info(message) end

---Warning level logging
---@param message string
function engine.log_warn(message) end

-- ==================== Asset Loading ====================

---Load a font from file
---@param id string
---@param path string
---@param size integer
function engine.load_font(id, path, size) end

---Load music from file
---@param id string
---@param path string
function engine.load_music(id, path) end

---Load a sound effect from file
---@param id string
---@param path string
function engine.load_sound(id, path) end

---Load a texture from file
---@param id string
---@param path string
function engine.load_texture(id, path) end

---Load a tilemap from file
---@param id string
---@param path string
function engine.load_tilemap(id, path) end

-- ==================== Entity Spawning ====================

---Clone a registered entity with optional overrides
---@param source_key string
---@return EntityBuilder
function engine.clone(source_key) end

---Create a new entity builder
---@return EntityBuilder
function engine.spawn() end

-- ==================== Audio Playback ====================

---Play music track
---@param id string
---@param looped boolean
function engine.play_music(id, looped) end

---Play a sound effect
---@param id string
function engine.play_sound(id) end

---Stop all playing music
function engine.stop_all_music() end

---Stop all playing sounds
function engine.stop_all_sounds() end

-- ==================== World Signals ====================

---Clear a world signal flag
---@param key string
function engine.clear_flag(key) end

---Clear a world signal integer
---@param key string
function engine.clear_integer(key) end

---Clear a world signal scalar
---@param key string
function engine.clear_scalar(key) end

---Clear a world signal string
---@param key string
function engine.clear_string(key) end

---Get a registered entity ID by key
---@param key string
---@return integer|nil
function engine.get_entity(key) end

---Get the count of entities in a tracked group
---@param group string
---@return integer|nil
function engine.get_group_count(group) end

---Get a world signal integer value
---@param key string
---@return integer|nil
function engine.get_integer(key) end

---Get a world signal scalar value
---@param key string
---@return number|nil
function engine.get_scalar(key) end

---Get a world signal string value
---@param key string
---@return string|nil
function engine.get_string(key) end

---Check if a world signal flag is set
---@param key string
---@return boolean
function engine.has_flag(key) end

---Remove a registered entity from world signals
---@param key string
function engine.remove_entity(key) end

---Register an entity ID in world signals
---@param key string
---@param entity_id integer
function engine.set_entity(key, entity_id) end

---Set a world signal flag
---@param key string
function engine.set_flag(key) end

---Set a world signal integer value
---@param key string
---@param value integer
function engine.set_integer(key, value) end

---Set a world signal scalar value
---@param key string
---@param value number
function engine.set_scalar(key, value) end

---Set a world signal string value
---@param key string
---@param value string
function engine.set_string(key, value) end

-- ==================== Phase Control ====================

---Transition an entity to a new phase
---@param entity_id integer
---@param phase string
function engine.phase_transition(entity_id, phase) end

-- ==================== Entity Commands ====================

---Add a named acceleration force to an entity
---@param entity_id integer
---@param name string
---@param x number
---@param y number
---@param enabled boolean
function engine.collision_entity_add_force(entity_id, name, x, y, enabled) end

---Despawn an entity
---@param entity_id integer
function engine.collision_entity_despawn(entity_id) end

---Freeze entity (zero velocity, ignore forces)
---@param entity_id integer
function engine.collision_entity_freeze(entity_id) end

---Insert a Lua timer on an entity
---@param entity_id integer
---@param duration number
---@param callback string
function engine.collision_entity_insert_lua_timer(entity_id, duration, callback) end

---Attach entity to a target entity
---@param entity_id integer
---@param target_id integer
---@param follow_x boolean
---@param follow_y boolean
---@param offset_x number
---@param offset_y number
---@param stored_vx number
---@param stored_vy number
function engine.collision_entity_insert_stuckto(entity_id, target_id, follow_x, follow_y, offset_x, offset_y, stored_vx, stored_vy) end

---Insert a time-to-live component on an entity
---@param entity_id integer
---@param seconds number
function engine.collision_entity_insert_ttl(entity_id, seconds) end

---Insert a position tween on an entity
---@param entity_id integer
---@param from_x number
---@param from_y number
---@param to_x number
---@param to_y number
---@param duration number
---@param easing string
---@param loop_mode string
---@param backwards boolean
function engine.collision_entity_insert_tween_position(entity_id, from_x, from_y, to_x, to_y, duration, easing, loop_mode, backwards) end

---Insert a rotation tween on an entity
---@param entity_id integer
---@param from number
---@param to number
---@param duration number
---@param easing string
---@param loop_mode string
---@param backwards boolean
function engine.collision_entity_insert_tween_rotation(entity_id, from, to, duration, easing, loop_mode, backwards) end

---Insert a scale tween on an entity
---@param entity_id integer
---@param from_x number
---@param from_y number
---@param to_x number
---@param to_y number
---@param duration number
---@param easing string
---@param loop_mode string
---@param backwards boolean
function engine.collision_entity_insert_tween_scale(entity_id, from_x, from_y, to_x, to_y, duration, easing, loop_mode, backwards) end

---Despawn a menu entity and its children
---@param entity_id integer
function engine.collision_entity_menu_despawn(entity_id) end

---Remove a named force from an entity
---@param entity_id integer
---@param name string
function engine.collision_entity_remove_force(entity_id, name) end

---Remove the Lua timer from an entity
---@param entity_id integer
function engine.collision_entity_remove_lua_timer(entity_id) end

---Remove per-entity shader
---@param entity_id integer
function engine.collision_entity_remove_shader(entity_id) end

---Remove entity tint
---@param entity_id integer
function engine.collision_entity_remove_tint(entity_id) end

---Remove position tween from an entity
---@param entity_id integer
function engine.collision_entity_remove_tween_position(entity_id) end

---Remove rotation tween from an entity
---@param entity_id integer
function engine.collision_entity_remove_tween_rotation(entity_id) end

---Remove scale tween from an entity
---@param entity_id integer
function engine.collision_entity_remove_tween_scale(entity_id) end

---Restart entity animation from frame 0
---@param entity_id integer
function engine.collision_entity_restart_animation(entity_id) end

---Set entity animation by key
---@param entity_id integer
---@param animation_key string
function engine.collision_entity_set_animation(entity_id, animation_key) end

---Enable or disable a named force on an entity
---@param entity_id integer
---@param name string
---@param enabled boolean
function engine.collision_entity_set_force_enabled(entity_id, name, enabled) end

---Set the acceleration value of a named force
---@param entity_id integer
---@param name string
---@param x number
---@param y number
function engine.collision_entity_set_force_value(entity_id, name, x, y) end

---Set entity friction
---@param entity_id integer
---@param friction number
function engine.collision_entity_set_friction(entity_id, friction) end

---Set entity max speed (nil to remove)
---@param entity_id integer
---@param max_speed number|nil
function engine.collision_entity_set_max_speed(entity_id, max_speed) end

---Set entity world position
---@param entity_id integer
---@param x number
---@param y number
function engine.collision_entity_set_position(entity_id, x, y) end

---Set entity rotation in degrees
---@param entity_id integer
---@param degrees number
function engine.collision_entity_set_rotation(entity_id, degrees) end

---Set entity scale
---@param entity_id integer
---@param sx number
---@param sy number
function engine.collision_entity_set_scale(entity_id, sx, sy) end

---Set per-entity shader by key
---@param entity_id integer
---@param key string
function engine.collision_entity_set_shader(entity_id, key) end

---Set entity speed (scales velocity to this magnitude)
---@param entity_id integer
---@param speed number
function engine.collision_entity_set_speed(entity_id, speed) end

---Set entity tint color (RGBA 0-255)
---@param entity_id integer
---@param r integer
---@param g integer
---@param b integer
---@param a integer
function engine.collision_entity_set_tint(entity_id, r, g, b, a) end

---Set entity velocity
---@param entity_id integer
---@param vx number
---@param vy number
function engine.collision_entity_set_velocity(entity_id, vx, vy) end

---Clear a uniform on entity shader
---@param entity_id integer
---@param name string
function engine.collision_entity_shader_clear_uniform(entity_id, name) end

---Clear all uniforms on entity shader
---@param entity_id integer
function engine.collision_entity_shader_clear_uniforms(entity_id) end

---Set a float uniform on entity shader
---@param entity_id integer
---@param name string
---@param value number
function engine.collision_entity_shader_set_float(entity_id, name, value) end

---Set an int uniform on entity shader
---@param entity_id integer
---@param name string
---@param value integer
function engine.collision_entity_shader_set_int(entity_id, name, value) end

---Set a vec2 uniform on entity shader
---@param entity_id integer
---@param name string
---@param x number
---@param y number
function engine.collision_entity_shader_set_vec2(entity_id, name, x, y) end

---Set a vec4 uniform on entity shader
---@param entity_id integer
---@param name string
---@param x number
---@param y number
---@param z number
---@param w number
function engine.collision_entity_shader_set_vec4(entity_id, name, x, y, z, w) end

---Clear a flag on an entity's signals
---@param entity_id integer
---@param flag string
function engine.collision_entity_signal_clear_flag(entity_id, flag) end

---Set a flag on an entity's signals
---@param entity_id integer
---@param flag string
function engine.collision_entity_signal_set_flag(entity_id, flag) end

---Set an integer signal on an entity
---@param entity_id integer
---@param key string
---@param value integer
function engine.collision_entity_signal_set_integer(entity_id, key, value) end

---Set a scalar signal on an entity
---@param entity_id integer
---@param key string
---@param value number
function engine.collision_entity_signal_set_scalar(entity_id, key, value) end

---Set a string signal on an entity
---@param entity_id integer
---@param key string
---@param value string
function engine.collision_entity_signal_set_string(entity_id, key, value) end

---Unfreeze entity
---@param entity_id integer
function engine.collision_entity_unfreeze(entity_id) end

---Release entity from its StuckTo target, restoring stored velocity
---@param entity_id integer
function engine.collision_release_stuckto(entity_id) end

---Add a named acceleration force to an entity
---@param entity_id integer
---@param name string
---@param x number
---@param y number
---@param enabled boolean
function engine.entity_add_force(entity_id, name, x, y, enabled) end

---Despawn an entity
---@param entity_id integer
function engine.entity_despawn(entity_id) end

---Freeze entity (zero velocity, ignore forces)
---@param entity_id integer
function engine.entity_freeze(entity_id) end

---Insert a Lua timer on an entity
---@param entity_id integer
---@param duration number
---@param callback string
function engine.entity_insert_lua_timer(entity_id, duration, callback) end

---Attach entity to a target entity
---@param entity_id integer
---@param target_id integer
---@param follow_x boolean
---@param follow_y boolean
---@param offset_x number
---@param offset_y number
---@param stored_vx number
---@param stored_vy number
function engine.entity_insert_stuckto(entity_id, target_id, follow_x, follow_y, offset_x, offset_y, stored_vx, stored_vy) end

---Insert a time-to-live component on an entity
---@param entity_id integer
---@param seconds number
function engine.entity_insert_ttl(entity_id, seconds) end

---Insert a position tween on an entity
---@param entity_id integer
---@param from_x number
---@param from_y number
---@param to_x number
---@param to_y number
---@param duration number
---@param easing string
---@param loop_mode string
---@param backwards boolean
function engine.entity_insert_tween_position(entity_id, from_x, from_y, to_x, to_y, duration, easing, loop_mode, backwards) end

---Insert a rotation tween on an entity
---@param entity_id integer
---@param from number
---@param to number
---@param duration number
---@param easing string
---@param loop_mode string
---@param backwards boolean
function engine.entity_insert_tween_rotation(entity_id, from, to, duration, easing, loop_mode, backwards) end

---Insert a scale tween on an entity
---@param entity_id integer
---@param from_x number
---@param from_y number
---@param to_x number
---@param to_y number
---@param duration number
---@param easing string
---@param loop_mode string
---@param backwards boolean
function engine.entity_insert_tween_scale(entity_id, from_x, from_y, to_x, to_y, duration, easing, loop_mode, backwards) end

---Despawn a menu entity and its children
---@param entity_id integer
function engine.entity_menu_despawn(entity_id) end

---Remove a named force from an entity
---@param entity_id integer
---@param name string
function engine.entity_remove_force(entity_id, name) end

---Remove the Lua timer from an entity
---@param entity_id integer
function engine.entity_remove_lua_timer(entity_id) end

---Remove per-entity shader
---@param entity_id integer
function engine.entity_remove_shader(entity_id) end

---Remove entity tint
---@param entity_id integer
function engine.entity_remove_tint(entity_id) end

---Remove position tween from an entity
---@param entity_id integer
function engine.entity_remove_tween_position(entity_id) end

---Remove rotation tween from an entity
---@param entity_id integer
function engine.entity_remove_tween_rotation(entity_id) end

---Remove scale tween from an entity
---@param entity_id integer
function engine.entity_remove_tween_scale(entity_id) end

---Restart entity animation from frame 0
---@param entity_id integer
function engine.entity_restart_animation(entity_id) end

---Set entity animation by key
---@param entity_id integer
---@param animation_key string
function engine.entity_set_animation(entity_id, animation_key) end

---Enable or disable a named force on an entity
---@param entity_id integer
---@param name string
---@param enabled boolean
function engine.entity_set_force_enabled(entity_id, name, enabled) end

---Set the acceleration value of a named force
---@param entity_id integer
---@param name string
---@param x number
---@param y number
function engine.entity_set_force_value(entity_id, name, x, y) end

---Set entity friction
---@param entity_id integer
---@param friction number
function engine.entity_set_friction(entity_id, friction) end

---Set entity max speed (nil to remove)
---@param entity_id integer
---@param max_speed number|nil
function engine.entity_set_max_speed(entity_id, max_speed) end

---Set entity world position
---@param entity_id integer
---@param x number
---@param y number
function engine.entity_set_position(entity_id, x, y) end

---Set entity rotation in degrees
---@param entity_id integer
---@param degrees number
function engine.entity_set_rotation(entity_id, degrees) end

---Set entity scale
---@param entity_id integer
---@param sx number
---@param sy number
function engine.entity_set_scale(entity_id, sx, sy) end

---Set per-entity shader by key
---@param entity_id integer
---@param key string
function engine.entity_set_shader(entity_id, key) end

---Set entity speed (scales velocity to this magnitude)
---@param entity_id integer
---@param speed number
function engine.entity_set_speed(entity_id, speed) end

---Set entity tint color (RGBA 0-255)
---@param entity_id integer
---@param r integer
---@param g integer
---@param b integer
---@param a integer
function engine.entity_set_tint(entity_id, r, g, b, a) end

---Set entity velocity
---@param entity_id integer
---@param vx number
---@param vy number
function engine.entity_set_velocity(entity_id, vx, vy) end

---Clear a uniform on entity shader
---@param entity_id integer
---@param name string
function engine.entity_shader_clear_uniform(entity_id, name) end

---Clear all uniforms on entity shader
---@param entity_id integer
function engine.entity_shader_clear_uniforms(entity_id) end

---Set a float uniform on entity shader
---@param entity_id integer
---@param name string
---@param value number
function engine.entity_shader_set_float(entity_id, name, value) end

---Set an int uniform on entity shader
---@param entity_id integer
---@param name string
---@param value integer
function engine.entity_shader_set_int(entity_id, name, value) end

---Set a vec2 uniform on entity shader
---@param entity_id integer
---@param name string
---@param x number
---@param y number
function engine.entity_shader_set_vec2(entity_id, name, x, y) end

---Set a vec4 uniform on entity shader
---@param entity_id integer
---@param name string
---@param x number
---@param y number
---@param z number
---@param w number
function engine.entity_shader_set_vec4(entity_id, name, x, y, z, w) end

---Clear a flag on an entity's signals
---@param entity_id integer
---@param flag string
function engine.entity_signal_clear_flag(entity_id, flag) end

---Set a flag on an entity's signals
---@param entity_id integer
---@param flag string
function engine.entity_signal_set_flag(entity_id, flag) end

---Set an integer signal on an entity
---@param entity_id integer
---@param key string
---@param value integer
function engine.entity_signal_set_integer(entity_id, key, value) end

---Set a scalar signal on an entity
---@param entity_id integer
---@param key string
---@param value number
function engine.entity_signal_set_scalar(entity_id, key, value) end

---Set a string signal on an entity
---@param entity_id integer
---@param key string
---@param value string
function engine.entity_signal_set_string(entity_id, key, value) end

---Unfreeze entity
---@param entity_id integer
function engine.entity_unfreeze(entity_id) end

---Release entity from its StuckTo target, restoring stored velocity
---@param entity_id integer
function engine.release_stuckto(entity_id) end

-- ==================== Group Tracking ====================

---Stop tracking all entity groups
function engine.clear_tracked_groups() end

---Check if a group is being tracked
---@param name string
---@return boolean
function engine.has_tracked_group(name) end

---Start tracking a named entity group
---@param name string
function engine.track_group(name) end

---Stop tracking a named entity group
---@param name string
function engine.untrack_group(name) end

-- ==================== Tilemap ====================

---Spawn tilemap entities from a loaded tilemap
---@param id string
function engine.spawn_tiles(id) end

-- ==================== Camera ====================

---Set the 2D camera target, offset, rotation and zoom
---@param target_x number
---@param target_y number
---@param offset_x number
---@param offset_y number
---@param rotation number
---@param zoom number
function engine.set_camera(target_x, target_y, offset_x, offset_y, rotation, zoom) end

-- ==================== Collision Commands ====================

---Clear a world signal flag (collision context)
---@param flag string
function engine.collision_clear_flag(flag) end

---Clear a world signal integer (collision context)
---@param key string
function engine.collision_clear_integer(key) end

---Clear a world signal scalar (collision context)
---@param key string
function engine.collision_clear_scalar(key) end

---Clear a world signal string (collision context)
---@param key string
function engine.collision_clear_string(key) end

---Clone a registered entity (collision context)
---@param source_key string
---@return CollisionEntityBuilder
function engine.collision_clone(source_key) end

---Transition an entity to a new phase (collision context)
---@param entity_id integer
---@param phase string
function engine.collision_phase_transition(entity_id, phase) end

---Play a sound effect (collision context)
---@param id string
function engine.collision_play_sound(id) end

---Set the 2D camera (collision context)
---@param target_x number
---@param target_y number
---@param offset_x number
---@param offset_y number
---@param rotation number
---@param zoom number
function engine.collision_set_camera(target_x, target_y, offset_x, offset_y, rotation, zoom) end

---Set a world signal flag (collision context)
---@param flag string
function engine.collision_set_flag(flag) end

---Set a world signal integer (collision context)
---@param key string
---@param value integer
function engine.collision_set_integer(key, value) end

---Set a world signal scalar (collision context)
---@param key string
---@param value number
function engine.collision_set_scalar(key, value) end

---Set a world signal string (collision context)
---@param key string
---@param value string
function engine.collision_set_string(key, value) end

---Create a new entity builder (collision context)
---@return CollisionEntityBuilder
function engine.collision_spawn() end

-- ==================== Animation Registration ====================

---Register an animation definition
---@param id string
---@param tex_key string
---@param pos_x number
---@param pos_y number
---@param displacement number
---@param frame_count integer
---@param fps number
---@param looped boolean
function engine.register_animation(id, tex_key, pos_x, pos_y, displacement, frame_count, fps, looped) end

-- ==================== Rendering & Shaders ====================

---Load a shader (at least one of vs_path/fs_path required)
---@param id string
---@param vs_path string|nil
---@param fs_path string|nil
function engine.load_shader(id, vs_path, fs_path) end

---Clear a uniform on post-process shader
---@param name string
function engine.post_process_clear_uniform(name) end

---Clear all uniforms on post-process shader
function engine.post_process_clear_uniforms() end

---Set a float uniform on post-process shader
---@param name string
---@param value number
function engine.post_process_set_float(name, value) end

---Set an int uniform on post-process shader
---@param name string
---@param value integer
function engine.post_process_set_int(name, value) end

---Set a vec2 uniform on post-process shader
---@param name string
---@param x number
---@param y number
function engine.post_process_set_vec2(name, x, y) end

---Set a vec4 uniform on post-process shader
---@param name string
---@param x number
---@param y number
---@param z number
---@param w number
function engine.post_process_set_vec4(name, x, y, z, w) end

---Set active post-processing shader chain (nil to clear)
---@param shader_ids string[]|nil
function engine.post_process_shader(shader_ids) end

-- ==================== Entity Builder ====================

---@class EntityBuilder
---Fluent builder for entity construction (regular context)
local EntityBuilder = {}

---Add a named acceleration force
---@param name string
---@param x number
---@param y number
---@param enabled boolean
---@return EntityBuilder
function EntityBuilder:with_accel(name, x, y, enabled) end

---Set animation by key
---@param animation_key string
---@return EntityBuilder
function EntityBuilder:with_animation(animation_key) end

---Add animation controller with fallback
---@param fallback_key string
---@return EntityBuilder
function EntityBuilder:with_animation_controller(fallback_key) end

---Add animation rule to controller
---@param condition_table table @see AnimationRuleCondition
---@param set_key string
---@return EntityBuilder
function EntityBuilder:with_animation_rule(condition_table, set_key) end

---Set box collider
---@param width number
---@param height number
---@param origin_x number
---@param origin_y number
---@return EntityBuilder
function EntityBuilder:with_collider(width, height, origin_x, origin_y) end

---Set collider offset
---@param offset_x number
---@param offset_y number
---@return EntityBuilder
function EntityBuilder:with_collider_offset(offset_x, offset_y) end

---Set friction (creates RigidBody if needed)
---@param friction number
---@return EntityBuilder
function EntityBuilder:with_friction(friction) end

---Mark entity as frozen (physics skipped)
---@return EntityBuilder
function EntityBuilder:with_frozen() end

---Spawn entities from a JSON grid layout
---@param path string
---@param group string
---@param zindex number
---@return EntityBuilder
function EntityBuilder:with_grid_layout(path, group, zindex) end

---Set entity group
---@param name string
---@return EntityBuilder
function EntityBuilder:with_group(name) end

---Add collision callback between two groups
---@param group_a string
---@param group_b string
---@param callback string
---@return EntityBuilder
function EntityBuilder:with_lua_collision_rule(group_a, group_b, callback) end

---Add a Lua timer callback
---@param duration number
---@param callback string
---@return EntityBuilder
function EntityBuilder:with_lua_timer(duration, callback) end

---Set max speed clamp (creates RigidBody if needed)
---@param speed number
---@return EntityBuilder
function EntityBuilder:with_max_speed(speed) end

---Add interactive menu
---@param items table @see MenuItem[]
---@param origin_x number
---@param origin_y number
---@param font string
---@param font_size number
---@param item_spacing number
---@param use_screen_space boolean
---@return EntityBuilder
function EntityBuilder:with_menu(items, origin_x, origin_y, font, font_size, item_spacing, use_screen_space) end

---Set quit action for menu item
---@param item_id string
---@return EntityBuilder
function EntityBuilder:with_menu_action_quit(item_id) end

---Set scene-switch action for menu item
---@param item_id string
---@param scene string
---@return EntityBuilder
function EntityBuilder:with_menu_action_set_scene(item_id, scene) end

---Set submenu action for menu item
---@param item_id string
---@param submenu string
---@return EntityBuilder
function EntityBuilder:with_menu_action_show_submenu(item_id, submenu) end

---Set Lua callback for menu selection
---@param callback string
---@return EntityBuilder
function EntityBuilder:with_menu_callback(callback) end

---Set menu normal/selected colors (RGBA)
---@param nr integer
---@param ng integer
---@param nb integer
---@param na integer
---@param sr integer
---@param sg integer
---@param sb integer
---@param sa integer
---@return EntityBuilder
function EntityBuilder:with_menu_colors(nr, ng, nb, na, sr, sg, sb, sa) end

---Set cursor entity for menu
---@param key string
---@return EntityBuilder
function EntityBuilder:with_menu_cursor(key) end

---Enable dynamic text updates for menu items
---@param dynamic boolean
---@return EntityBuilder
function EntityBuilder:with_menu_dynamic_text(dynamic) end

---Set sound for menu selection changes
---@param sound_key string
---@return EntityBuilder
function EntityBuilder:with_menu_selection_sound(sound_key) end

---Set max visible menu items (enables scrolling)
---@param count integer
---@return EntityBuilder
function EntityBuilder:with_menu_visible_count(count) end

---Enable mouse position tracking
---@param follow_x boolean
---@param follow_y boolean
---@return EntityBuilder
function EntityBuilder:with_mouse_controlled(follow_x, follow_y) end

---Add particle emitter
---@param table table @see ParticleEmitterConfig
---@return EntityBuilder
function EntityBuilder:with_particle_emitter(table) end

---Survive scene transitions
---@return EntityBuilder
function EntityBuilder:with_persistent() end

---Add phase state machine
---@param table table @see PhaseDefinition
---@return EntityBuilder
function EntityBuilder:with_phase(table) end

---Set world position
---@param x number
---@param y number
---@return EntityBuilder
function EntityBuilder:with_position(x, y) end

---Set rotation in degrees
---@param degrees number
---@return EntityBuilder
function EntityBuilder:with_rotation(degrees) end

---Set scale
---@param sx number
---@param sy number
---@return EntityBuilder
function EntityBuilder:with_scale(sx, sy) end

---Set screen position (UI elements)
---@param x number
---@param y number
---@return EntityBuilder
function EntityBuilder:with_screen_position(x, y) end

---Set per-entity shader with optional uniforms
---@param shader_key string
---@param uniforms table|nil
---@return EntityBuilder
function EntityBuilder:with_shader(shader_key, uniforms) end

---Bind text to a WorldSignal value
---@param key string
---@return EntityBuilder
function EntityBuilder:with_signal_binding(key) end

---Set format string for signal binding (use {} as placeholder)
---@param format string
---@return EntityBuilder
function EntityBuilder:with_signal_binding_format(format) end

---Add a flag signal
---@param key string
---@return EntityBuilder
function EntityBuilder:with_signal_flag(key) end

---Add an integer signal
---@param key string
---@param value integer
---@return EntityBuilder
function EntityBuilder:with_signal_integer(key, value) end

---Add a scalar signal
---@param key string
---@param value number
---@return EntityBuilder
function EntityBuilder:with_signal_scalar(key, value) end

---Add a string signal
---@param key string
---@param value string
---@return EntityBuilder
function EntityBuilder:with_signal_string(key, value) end

---Add empty Signals component
---@return EntityBuilder
function EntityBuilder:with_signals() end

---Set sprite
---@param tex_key string
---@param width number
---@param height number
---@param origin_x number
---@param origin_y number
---@return EntityBuilder
function EntityBuilder:with_sprite(tex_key, width, height, origin_x, origin_y) end

---Set sprite flipping
---@param flip_h boolean
---@param flip_v boolean
---@return EntityBuilder
function EntityBuilder:with_sprite_flip(flip_h, flip_v) end

---Set sprite offset
---@param offset_x number
---@param offset_y number
---@return EntityBuilder
function EntityBuilder:with_sprite_offset(offset_x, offset_y) end

---Attach entity to a target entity
---@param target_entity_id integer
---@param follow_x boolean
---@param follow_y boolean
---@return EntityBuilder
function EntityBuilder:with_stuckto(target_entity_id, follow_x, follow_y) end

---Set offset for StuckTo
---@param offset_x number
---@param offset_y number
---@return EntityBuilder
function EntityBuilder:with_stuckto_offset(offset_x, offset_y) end

---Set velocity to restore when unstuck
---@param vx number
---@param vy number
---@return EntityBuilder
function EntityBuilder:with_stuckto_stored_velocity(vx, vy) end

---Set DynamicText component
---@param content string
---@param font string
---@param font_size number
---@param r integer
---@param g integer
---@param b integer
---@param a integer
---@return EntityBuilder
function EntityBuilder:with_text(content, font, font_size, r, g, b, a) end

---Set color tint (RGBA 0-255)
---@param r integer
---@param g integer
---@param b integer
---@param a integer
---@return EntityBuilder
function EntityBuilder:with_tint(r, g, b, a) end

---Set time-to-live (auto-despawn)
---@param seconds number
---@return EntityBuilder
function EntityBuilder:with_ttl(seconds) end

---Add position tween animation
---@param from_x number
---@param from_y number
---@param to_x number
---@param to_y number
---@param duration number
---@return EntityBuilder
function EntityBuilder:with_tween_position(from_x, from_y, to_x, to_y, duration) end

---Start position tween in reverse
---@return EntityBuilder
function EntityBuilder:with_tween_position_backwards() end

---Set easing for position tween
---@param easing string
---@return EntityBuilder
function EntityBuilder:with_tween_position_easing(easing) end

---Set loop mode for position tween
---@param loop_mode string
---@return EntityBuilder
function EntityBuilder:with_tween_position_loop(loop_mode) end

---Add rotation tween animation
---@param from number
---@param to number
---@param duration number
---@return EntityBuilder
function EntityBuilder:with_tween_rotation(from, to, duration) end

---Start rotation tween in reverse
---@return EntityBuilder
function EntityBuilder:with_tween_rotation_backwards() end

---Set easing for rotation tween
---@param easing string
---@return EntityBuilder
function EntityBuilder:with_tween_rotation_easing(easing) end

---Set loop mode for rotation tween
---@param loop_mode string
---@return EntityBuilder
function EntityBuilder:with_tween_rotation_loop(loop_mode) end

---Add scale tween animation
---@param from_x number
---@param from_y number
---@param to_x number
---@param to_y number
---@param duration number
---@return EntityBuilder
function EntityBuilder:with_tween_scale(from_x, from_y, to_x, to_y, duration) end

---Start scale tween in reverse
---@return EntityBuilder
function EntityBuilder:with_tween_scale_backwards() end

---Set easing for scale tween
---@param easing string
---@return EntityBuilder
function EntityBuilder:with_tween_scale_easing(easing) end

---Set loop mode for scale tween
---@param loop_mode string
---@return EntityBuilder
function EntityBuilder:with_tween_scale_loop(loop_mode) end

---Set velocity (creates RigidBody if needed)
---@param vx number
---@param vy number
---@return EntityBuilder
function EntityBuilder:with_velocity(vx, vy) end

---Set render order
---@param z number
---@return EntityBuilder
function EntityBuilder:with_zindex(z) end

---Register entity in WorldSignals for later retrieval
---@param key string
---@return EntityBuilder
function EntityBuilder:register_as(key) end

---Queue entity for spawning or cloning
function EntityBuilder:build() end

-- ==================== Collision Entity Builder ====================

---@class CollisionEntityBuilder
---Fluent builder for entity construction (collision context)
local CollisionEntityBuilder = {}

---Add a named acceleration force
---@param name string
---@param x number
---@param y number
---@param enabled boolean
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_accel(name, x, y, enabled) end

---Set animation by key
---@param animation_key string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_animation(animation_key) end

---Add animation controller with fallback
---@param fallback_key string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_animation_controller(fallback_key) end

---Add animation rule to controller
---@param condition_table table @see AnimationRuleCondition
---@param set_key string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_animation_rule(condition_table, set_key) end

---Set box collider
---@param width number
---@param height number
---@param origin_x number
---@param origin_y number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_collider(width, height, origin_x, origin_y) end

---Set collider offset
---@param offset_x number
---@param offset_y number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_collider_offset(offset_x, offset_y) end

---Set friction (creates RigidBody if needed)
---@param friction number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_friction(friction) end

---Mark entity as frozen (physics skipped)
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_frozen() end

---Spawn entities from a JSON grid layout
---@param path string
---@param group string
---@param zindex number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_grid_layout(path, group, zindex) end

---Set entity group
---@param name string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_group(name) end

---Add collision callback between two groups
---@param group_a string
---@param group_b string
---@param callback string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_lua_collision_rule(group_a, group_b, callback) end

---Add a Lua timer callback
---@param duration number
---@param callback string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_lua_timer(duration, callback) end

---Set max speed clamp (creates RigidBody if needed)
---@param speed number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_max_speed(speed) end

---Add interactive menu
---@param items table @see MenuItem[]
---@param origin_x number
---@param origin_y number
---@param font string
---@param font_size number
---@param item_spacing number
---@param use_screen_space boolean
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_menu(items, origin_x, origin_y, font, font_size, item_spacing, use_screen_space) end

---Set quit action for menu item
---@param item_id string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_menu_action_quit(item_id) end

---Set scene-switch action for menu item
---@param item_id string
---@param scene string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_menu_action_set_scene(item_id, scene) end

---Set submenu action for menu item
---@param item_id string
---@param submenu string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_menu_action_show_submenu(item_id, submenu) end

---Set Lua callback for menu selection
---@param callback string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_menu_callback(callback) end

---Set menu normal/selected colors (RGBA)
---@param nr integer
---@param ng integer
---@param nb integer
---@param na integer
---@param sr integer
---@param sg integer
---@param sb integer
---@param sa integer
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_menu_colors(nr, ng, nb, na, sr, sg, sb, sa) end

---Set cursor entity for menu
---@param key string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_menu_cursor(key) end

---Enable dynamic text updates for menu items
---@param dynamic boolean
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_menu_dynamic_text(dynamic) end

---Set sound for menu selection changes
---@param sound_key string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_menu_selection_sound(sound_key) end

---Set max visible menu items (enables scrolling)
---@param count integer
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_menu_visible_count(count) end

---Enable mouse position tracking
---@param follow_x boolean
---@param follow_y boolean
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_mouse_controlled(follow_x, follow_y) end

---Add particle emitter
---@param table table @see ParticleEmitterConfig
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_particle_emitter(table) end

---Survive scene transitions
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_persistent() end

---Add phase state machine
---@param table table @see PhaseDefinition
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_phase(table) end

---Set world position
---@param x number
---@param y number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_position(x, y) end

---Set rotation in degrees
---@param degrees number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_rotation(degrees) end

---Set scale
---@param sx number
---@param sy number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_scale(sx, sy) end

---Set screen position (UI elements)
---@param x number
---@param y number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_screen_position(x, y) end

---Set per-entity shader with optional uniforms
---@param shader_key string
---@param uniforms table|nil
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_shader(shader_key, uniforms) end

---Bind text to a WorldSignal value
---@param key string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_signal_binding(key) end

---Set format string for signal binding (use {} as placeholder)
---@param format string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_signal_binding_format(format) end

---Add a flag signal
---@param key string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_signal_flag(key) end

---Add an integer signal
---@param key string
---@param value integer
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_signal_integer(key, value) end

---Add a scalar signal
---@param key string
---@param value number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_signal_scalar(key, value) end

---Add a string signal
---@param key string
---@param value string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_signal_string(key, value) end

---Add empty Signals component
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_signals() end

---Set sprite
---@param tex_key string
---@param width number
---@param height number
---@param origin_x number
---@param origin_y number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_sprite(tex_key, width, height, origin_x, origin_y) end

---Set sprite flipping
---@param flip_h boolean
---@param flip_v boolean
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_sprite_flip(flip_h, flip_v) end

---Set sprite offset
---@param offset_x number
---@param offset_y number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_sprite_offset(offset_x, offset_y) end

---Attach entity to a target entity
---@param target_entity_id integer
---@param follow_x boolean
---@param follow_y boolean
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_stuckto(target_entity_id, follow_x, follow_y) end

---Set offset for StuckTo
---@param offset_x number
---@param offset_y number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_stuckto_offset(offset_x, offset_y) end

---Set velocity to restore when unstuck
---@param vx number
---@param vy number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_stuckto_stored_velocity(vx, vy) end

---Set DynamicText component
---@param content string
---@param font string
---@param font_size number
---@param r integer
---@param g integer
---@param b integer
---@param a integer
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_text(content, font, font_size, r, g, b, a) end

---Set color tint (RGBA 0-255)
---@param r integer
---@param g integer
---@param b integer
---@param a integer
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tint(r, g, b, a) end

---Set time-to-live (auto-despawn)
---@param seconds number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_ttl(seconds) end

---Add position tween animation
---@param from_x number
---@param from_y number
---@param to_x number
---@param to_y number
---@param duration number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_position(from_x, from_y, to_x, to_y, duration) end

---Start position tween in reverse
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_position_backwards() end

---Set easing for position tween
---@param easing string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_position_easing(easing) end

---Set loop mode for position tween
---@param loop_mode string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_position_loop(loop_mode) end

---Add rotation tween animation
---@param from number
---@param to number
---@param duration number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_rotation(from, to, duration) end

---Start rotation tween in reverse
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_rotation_backwards() end

---Set easing for rotation tween
---@param easing string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_rotation_easing(easing) end

---Set loop mode for rotation tween
---@param loop_mode string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_rotation_loop(loop_mode) end

---Add scale tween animation
---@param from_x number
---@param from_y number
---@param to_x number
---@param to_y number
---@param duration number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_scale(from_x, from_y, to_x, to_y, duration) end

---Start scale tween in reverse
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_scale_backwards() end

---Set easing for scale tween
---@param easing string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_scale_easing(easing) end

---Set loop mode for scale tween
---@param loop_mode string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_tween_scale_loop(loop_mode) end

---Set velocity (creates RigidBody if needed)
---@param vx number
---@param vy number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_velocity(vx, vy) end

---Set render order
---@param z number
---@return CollisionEntityBuilder
function CollisionEntityBuilder:with_zindex(z) end

---Register entity in WorldSignals for later retrieval
---@param key string
---@return CollisionEntityBuilder
function CollisionEntityBuilder:register_as(key) end

---Queue entity for spawning or cloning
function CollisionEntityBuilder:build() end

